### ISSUE TITLE
文件删除异常(File delete error)

### ISSUE THREAD

**Issue by huzhenjie** [MiCode/FileExplorer#35]
```
10-12 10:53:26.501  11263-21748/net.micode.fileexplorer E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: net.micode.fileexplorer, PID: 11263
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=11263, uid=10739
            at android.os.Parcel.readException(Parcel.java:1472)
            at android.os.Parcel.readException(Parcel.java:1426)
            at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:2383)
            at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1159)
            at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:365)
            at net.micode.fileexplorer.FileViewInteractionHub.notifyFileSystemChanged(FileViewInteractionHub.java:591)
            at net.micode.fileexplorer.FileViewInteractionHub.onFileChanged(FileViewInteractionHub.java:1090)
            at net.micode.fileexplorer.FileOperationHelper$4.run(FileOperationHelper.java:218)
            at net.micode.fileexplorer.FileOperationHelper$3.doInBackground(FileOperationHelper.java:164)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
10-12 10:53:27.111  11263-11263/net.micode.fileexplorer E/WindowManager﹕ android.view.WindowLeaked: Activity net.micode.fileexplorer.FileExplorerTabActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{43eeb120 V.E..... R......D 0,0-1026,288} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:249)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:286)
            at net.micode.fileexplorer.FileViewInteractionHub.showProgress(FileViewInteractionHub.java:109)
            at net.micode.fileexplorer.FileViewInteractionHub.access$900(FileViewInteractionHub.java:65)
            at net.micode.fileexplorer.FileViewInteractionHub$7.onClick(FileViewInteractionHub.java:615)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5047)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by zhanlan123** [comment]
权限问题，加入当前系统的keystore

**Comment by glitchphan** [comment]
How do you fix this issue? The app crashes when I try to delete a file.
